name: install_python
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
 test:
   runs-on: [ ubuntu-latest ]
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: install python
       uses: actions/setup-python@v5 
       with:
          python-version: '3.10'
     - name: run script
       run: python app.py
       
